# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hodl.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1086, 599)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/hodl.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(0, 0, 1061, 541))
        self.Tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.Tabs.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.Tabs.setObjectName("Tabs")
        self.Mywallet = QtWidgets.QWidget()
        self.Mywallet.setObjectName("Mywallet")
        self.label = QtWidgets.QLabel(self.Mywallet)
        self.label.setGeometry(QtCore.QRect(20, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.money = QtWidgets.QLabel(self.Mywallet)
        self.money.setGeometry(QtCore.QRect(40, 60, 86, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.money.setFont(font)
        self.money.setObjectName("money")
        self.label_2 = QtWidgets.QLabel(self.Mywallet)
        self.label_2.setGeometry(QtCore.QRect(10, 230, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.Mywallet)
        self.lineEdit.setGeometry(QtCore.QRect(10, 270, 481, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Mywallet)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 310, 151, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tabWidget = QtWidgets.QTabWidget(self.Mywallet)
        self.tabWidget.setGeometry(QtCore.QRect(520, 0, 521, 491))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 481, 421))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 10, 481, 421))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab_4)
        self.textBrowser_3.setGeometry(QtCore.QRect(20, 20, 481, 421))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.tab_5)
        self.textBrowser_4.setGeometry(QtCore.QRect(10, 20, 481, 421))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.tabWidget.addTab(self.tab_5, "")
        self.label_3 = QtWidgets.QLabel(self.Mywallet)
        self.label_3.setGeometry(QtCore.QRect(320, 30, 141, 21))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.Mywallet)
        self.comboBox.setGeometry(QtCore.QRect(320, 70, 113, 31))
        self.comboBox.setObjectName("comboBox")
        self.label_4 = QtWidgets.QLabel(self.Mywallet)
        self.label_4.setGeometry(QtCore.QRect(40, 120, 151, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Mywallet)
        self.label_5.setGeometry(QtCore.QRect(40, 160, 291, 21))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.Mywallet)
        self.pushButton.setGeometry(QtCore.QRect(380, 160, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.Tabs.addTab(self.Mywallet, "")
        self.Smart_contracts = QtWidgets.QWidget()
        self.Smart_contracts.setObjectName("Smart_contracts")
        self.Tabs.addTab(self.Smart_contracts, "")
        self.Trade = QtWidgets.QWidget()
        self.Trade.setObjectName("Trade")
        self.Tabs.addTab(self.Trade, "")
        self.Network = QtWidgets.QWidget()
        self.Network.setObjectName("Network")
        self.Tabs.addTab(self.Network, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1086, 29))
        self.menubar.setObjectName("menubar")
        self.menuHODL = QtWidgets.QMenu(self.menubar)
        self.menuHODL.setObjectName("menuHODL")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionWallet = QtWidgets.QAction(MainWindow)
        self.actionWallet.setObjectName("actionWallet")
        self.actionOpen_wallet = QtWidgets.QAction(MainWindow)
        self.actionOpen_wallet.setObjectName("actionOpen_wallet")
        self.actionNew_wallet = QtWidgets.QAction(MainWindow)
        self.actionNew_wallet.setObjectName("actionNew_wallet")
        self.actionSmart_contract = QtWidgets.QAction(MainWindow)
        self.actionSmart_contract.setObjectName("actionSmart_contract")
        self.actionVirtual_decentralized_storage = QtWidgets.QAction(MainWindow)
        self.actionVirtual_decentralized_storage.setObjectName("actionVirtual_decentralized_storage")
        self.menuHODL.addAction(self.actionOpen_wallet)
        self.menuHODL.addAction(self.actionNew_wallet)
        self.menuNew.addAction(self.actionSmart_contract)
        self.menuNew.addAction(self.actionVirtual_decentralized_storage)
        self.menubar.addAction(self.menuHODL.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuNew.menuAction())

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HODL"))
        self.label.setText(_translate("MainWindow", "My money:"))
        self.money.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "New transaction:"))
        self.lineEdit.setText(_translate("MainWindow", "To:"))
        self.lineEdit_2.setText(_translate("MainWindow", "How much:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "My tokens"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "My transactions"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "My contracts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "My disks"))
        self.label_3.setText(_translate("MainWindow", "Choose wallet:"))
        self.label_4.setText(_translate("MainWindow", "Current wallet:"))
        self.pushButton.setText(_translate("MainWindow", "Copy"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Mywallet), _translate("MainWindow", "My wallet"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Smart_contracts), _translate("MainWindow", "Smart contracts"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Trade), _translate("MainWindow", "Trade"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Network), _translate("MainWindow", "Network"))
        self.menuHODL.setTitle(_translate("MainWindow", "Wallet"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuNew.setTitle(_translate("MainWindow", "New"))
        self.actionWallet.setText(_translate("MainWindow", "Wallet"))
        self.actionOpen_wallet.setText(_translate("MainWindow", "Open wallet"))
        self.actionNew_wallet.setText(_translate("MainWindow", "New wallet"))
        self.actionSmart_contract.setText(_translate("MainWindow", "Smart contract"))
        self.actionVirtual_decentralized_storage.setText(_translate("MainWindow", "Virtual decentralized storage"))

